const SCREENS = {
    ONBOARDING: 'ONBOARDING',
    SIGNUP: 'SIGNUP',
    VERIFICATION: 'VERIFICATION',
    SIGNIN: 'SIGNIN',
    HOME: 'HOME',
    DETAIL: 'DETAILS',
    QUIZ: 'QUIZ',
    PROFILE: "PROFILE",
    FORGOT_PASSWORD: "FORGOT_PASSWORD",
    PASSWORD_OTP: "PASSWORD_OTP",
    RESET_PASSWORD: "RESET_PASSWORD",
    STATISTICS: "STATISTICS",
    EDIT_PROFILE : "EDIT_PROFILE",
    NOTIFICATION_SETTINGS : 'NOTIFICATION_SETTINGS',
    LEADER_BOARD : 'LEADER_BOARD',
    CONTACT_SCREEN: 'CONTACT_SCREEN',
    HELP_SCREEN: 'HELP_SCREEN',
    PRIVACY_POLICY: 'PRIVACY_POLICY',
    PHONE_NUMBER_VERIFICATION: 'PHONE_NUMBER_VERIFICATION',
    FAQ: 'FAQ',
    QUIZ_ENTRY: 'QUIZ_ENTRY',
    SELECT_CATEGORY: 'SELECT_CATEGORY'
}

export { SCREENS }